name: Render Remotion Video

on:
  push:
    branches:
      - main # mainブランチにプッシュされたら実行
    paths:
      - 'scenario.md' # scenario.mdが変更されたら実行

jobs:
  render:
    runs-on: ubuntu-latest # Linux環境で実行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # コードをチェックアウト

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Node.jsのバージョンを指定

      - name: Install dependencies
        run: npm ci # 依存関係をインストール

      - name: Generate scenario.json
        run: node scripts/generate-scenario.js # scenario.jsonを生成

      - name: Render video
        run: npx remotion render src/index.ts MyVideo out/video.mp4 # 動画をレンダリング

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: out/video.mp4 # レンダリングされた動画をアップロード
